# Basic `dependabot.yml` file with
# minimum configuration for two package managers

version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    # Check for updates every day (weekdays)
    schedule:
      interval: "daily"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for a `Dockerfile` in the `root` directory
    directory: "/"
    # Check for updates every day (weekdays)
    schedule:
      interval: "daily"
